export const SET_CURRENT_FONT_SIZE = 'SET_CURRENT_FONT_SIZE'

// ui
export const TOGGLE_MODAL_VISIBILITY_STATUS = 'TOGGLE_MODAL_VISIBILITY_STATUS'

// auth
export const SET_USER_TO_AUTHENTICATED = 'SET_USER_TO_AUTHENTICATED'

// data
